

[versions]
# libraries
junit = "4.13.2"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.4.0"
kotlin = "2.1.20"
idea-ext = "1.1.10"
yumi-licenser = "2.1.1"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }

gradlePlugin-yumi-licenser = { module = "dev.yumi:yumi-gradle-licenser", version.ref = "yumi-licenser" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
idea-ext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "idea-ext" }
yumi-licenser = { id = "dev.yumi.gradle.licenser", version.ref = "yumi-licenser" }
